image: node:8.15.0

cache:
    paths:
        - node_modules/

all_tests:
    script:
        - yarn install
        - yarn global add nyc
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - nyc --reporter=lcov yarn run mocha --colors test
        - CC_TEST_REPORTER_ID=e5030292b1e57c0a42df0f32a6f4ac8cc6246340619d54ec60aa3822b6d6fec2 ./cc-test-reporter after-build