image: node:8.15.0

cache:
    paths:
        - node_modules/

all_tests:
    script:
        - yarn install
        - yarn global add nyc
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - nyc --reporter=lcov yarn run mocha --colors test
        - ./cc-test-reporter after-build