checks:
    javascript: true
build:
    environment:
        node: 14.15.0
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
filter:
    excluded_paths:
        - "coverage/" # only relevant on dev
        - "demo/"
        - "node_modules/"
        - "test/"
