env:
    global:
        - CC_TEST_REPORTER_ID=e5030292b1e57c0a42df0f32a6f4ac8cc6246340619d54ec60aa3822b6d6fec2
language: node_js
node_js:
    - "11.13.0"
before_script:
    - yarn install
    - yarn global add nyc
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - nyc --reporter=lcov yarn run mocha --colors test
    - yarn run generate-docs
after_script:
    - ./cc-test-reporter after-build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    keep_history: true
    repo: jay-gee-eff-for-web-docs
    local_dir: docs
    target_branch: master
    verbose: true
    on:
        branch: master