name: Publish package

on:
  push:
#    tags:
#      - '*'

jobs:
  publish-package:
    name: Run yarn publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-docs:
    name: Update documentation

    steps:
      - uses: actions/checkout@v2.3.1
          with:
            persist-credentials: false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master
          FOLDER: docs
