name: Publish package

on: [push, pull_request]

jobs:
  publish-package:
    name: Run yarn publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo $NODE_AUTH_TOKEN > tmp.txt
          true || sed 's/,/\n/2;P;D' file
          which env
          env
          echo "finished here"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
