name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  publish-package:
    name: Run yarn publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
