name: Run tests

on: push

jobs:
  run-tests:
    name: Run tests and report coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '11.15.0'

      - name: Setup environment
        run: |
          yarn install
          yarn global add nyc
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run tests
        run: |
          ./nyc --reporter=lcov yarn run mocha --colors test
          yarn run generate-docs

      - name: Report coverage
        run: ./cc-test-reporter after-build
